name: 'Quantum Merge'
description: 'Allows merging code from a given directory to a given repository'

inputs:
  deploy-key:
    description: 'SSH key to use for GitHub deployments'
    required: true
  username:
    description: 'GitHub user (or organization) associated for the destination repository'
    required: true
  repository:
    description: 'Name of the destination repository'
    required: true
  branch:
    description: 'Name of the branch the code should be pushed to'
    required: false
    default: 'main'
  directory:
    description: 'Name of the directory from which to perform the merge'
    required: true
  remote-directory:
    description: 'Name of the directory which the data should be installed to'
    required: false
  filter:
    description: 'The filter to apply to files cloned from the desination repository in order to merge changes'
    required: true
  commit-message:
    description: 'The message to associate with the commit'
    required: false
    default: ${{ github.event.head_commit.message }}

runs:
  using: "composite"
  steps:
    - name: Configure Git Credentials
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ inputs.deploy-key }}
    - name: Merge Code from ${{ inputs.directory }} to github.com:${{ inputs.username }}/${{ inputs.repository }}.git
      run: $GITHUB_ACTION_PATH/entrypoint.sh "${{ inputs.username }}" "${{ inputs.repository }}" "${{ inputs.branch }}" "${{ inputs.directory }}" "${{ inputs.remote-directory }}" "${{ inputs.filter }}" "${{ inputs.commit-message }}"
      shell: bash

branding:
  icon: git-commit
  color: blue
